name: Basic GitHub Actions Workflow

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  basic-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: tests
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        python3 -m pytest tests
          
       